# Generated by Django 5.0.6 on 2026-05-22 01:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cardType",
                    models.CharField(max_length=50, unique=True, verbose_name="卡型号"),
                ),
                ("totalCount", models.IntegerField(default=0, verbose_name="总数量")),
                (
                    "allocatedCount",
                    models.IntegerField(default=0, verbose_name="已分配数量"),
                ),
            ],
            options={
                "verbose_name": "资源库存",
                "verbose_name_plural": "资源库存管理",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("APPLICANT", "申请人"),
                            ("APPROVER", "审批人"),
                            ("EXECUTOR", "执行人"),
                            ("ADMIN", "管理员"),
                        ],
                        default="APPLICANT",
                        max_length=20,
                        verbose_name="用户角色",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "系统用户",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("users", models.TextField(verbose_name="使用人(多个)")),
                ("team", models.CharField(max_length=100, verbose_name="所在团队")),
                (
                    "cardForm",
                    models.CharField(max_length=100, verbose_name="申请卡形态"),
                ),
                (
                    "cardType",
                    models.CharField(max_length=100, verbose_name="申请卡型号"),
                ),
                ("purpose", models.TextField(verbose_name="申请用途")),
                ("project", models.CharField(max_length=100, verbose_name="受益项目")),
                (
                    "model_used",
                    models.CharField(max_length=100, verbose_name="使用的模型"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("HIGH", "高"), ("MEDIUM", "中"), ("LOW", "低")],
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                ("priorityReason", models.TextField(verbose_name="优先级理由")),
                ("count", models.IntegerField(verbose_name="申请数量")),
                ("minCount", models.IntegerField(verbose_name="最少数量")),
                (
                    "duration",
                    models.CharField(
                        default="最多使用两周", max_length=100, verbose_name="使用时间"
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审批"),
                            ("APPROVED", "已审批(待执行)"),
                            ("REJECTED", "已驳回"),
                            ("EXECUTED", "已执行"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "allocatedCount",
                    models.IntegerField(blank=True, null=True, verbose_name="分配数量"),
                ),
                (
                    "allocatedCardType",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配型号"
                    ),
                ),
                (
                    "allocatedCardForm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分配形态"
                    ),
                ),
                (
                    "approvalNote",
                    models.TextField(blank=True, null=True, verbose_name="审批意见"),
                ),
                (
                    "executionResult",
                    models.TextField(blank=True, null=True, verbose_name="执行结果"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源申请单",
                "verbose_name_plural": "资源申请单列表",
            },
        ),
        migrations.CreateModel(
            name="SystemOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TEAM", "所在团队"),
                            ("CARD_FORM", "卡资源形态"),
                            ("CARD_TYPE", "卡资源型号"),
                            ("PROJECT", "受益项目"),
                        ],
                        max_length=20,
                        verbose_name="选项类型",
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="选项值")),
            ],
            options={
                "verbose_name": "系统选项",
                "verbose_name_plural": "系统选项配置",
                "unique_together": {("category", "value")},
            },
        ),
    ]
