# Generated by Django 5.0.6 on 2026-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="allocatedCardName",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="分配卡资源名称"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="allocatedRegion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="分配地域"
            ),
        ),
        migrations.AddField(
            model_name="resourceinventory",
            name="cardForm",
            field=models.CharField(
                default="裸机", max_length=50, verbose_name="卡资源形态"
            ),
        ),
        migrations.AddField(
            model_name="resourceinventory",
            name="cardName",
            field=models.CharField(
                default="默认卡资源", max_length=100, verbose_name="卡资源名称"
            ),
        ),
        migrations.AddField(
            model_name="resourceinventory",
            name="region",
            field=models.CharField(
                default="北京", max_length=50, verbose_name="卡所在地域"
            ),
        ),
        migrations.AlterField(
            model_name="resourceinventory",
            name="cardType",
            field=models.CharField(max_length=50, verbose_name="卡资源型号"),
        ),
        migrations.AlterField(
            model_name="systemoption",
            name="category",
            field=models.CharField(
                choices=[
                    ("TEAM", "所在团队"),
                    ("CARD_FORM", "卡资源形态"),
                    ("CARD_TYPE", "卡资源型号"),
                    ("PROJECT", "受益项目"),
                    ("REGION", "地域"),
                ],
                max_length=20,
                verbose_name="选项类型",
            ),
        ),
    ]
