# Generated by Django 5.0.6 on 2026-05-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0002_application_allocatedcardname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待审批"),
                    ("APPROVED", "已审批(待执行)"),
                    ("REJECTED", "已驳回"),
                    ("EXECUTED", "已执行"),
                    ("CANCELLED", "已撤回"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
