# Generated by Django 5.0.6 on 2026-05-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0003_alter_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="endDate",
            field=models.DateField(blank=True, null=True, verbose_name="结束使用日期"),
        ),
        migrations.AddField(
            model_name="application",
            name="startDate",
            field=models.DateField(blank=True, null=True, verbose_name="开始使用日期"),
        ),
    ]
