# Generated by Django 5.0.6 on 2026-05-25 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0005_alter_application_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="资源名称")),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="密码"
                    ),
                ),
                (
                    "current_users",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="当前使用人"
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="卡资源型号"
                    ),
                ),
                (
                    "card_form",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="卡资源形态"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "闲置"),
                            ("IN_USE", "使用中"),
                            ("FAULT", "故障"),
                        ],
                        default="IDLE",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所在应用"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="地域"
                    ),
                ),
                (
                    "specifications",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="当前责任人(申请人)",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料资产",
                "verbose_name_plural": "物料资产管理",
            },
        ),
    ]
