# Generated by Django 5.0.6 on 2026-05-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0006_resourceasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceasset",
            name="allocated_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated_assets",
                to="resource_app.application",
                verbose_name="关联的申请单",
            ),
        ),
    ]
