# Generated by Django 5.0.6 on 2026-05-25 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0007_resourceasset_allocated_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="问题标题")),
                ("content", models.TextField(verbose_name="详细描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "待处理"), ("RESOLVED", "已解决")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="反馈人",
                    ),
                ),
            ],
            options={
                "verbose_name": "问题反馈",
                "verbose_name_plural": "问题反馈管理",
            },
        ),
    ]
