# Generated by Django 5.0.6 on 2026-05-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0008_issuefeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="attachments/", verbose_name="图片附件"
            ),
        ),
    ]
