# Generated by Django 5.0.6 on 2026-05-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0009_application_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="final_approver_note",
            field=models.TextField(
                blank=True, null=True, verbose_name="部门负责人终审意见"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="pre_approver_note",
            field=models.TextField(blank=True, null=True, verbose_name="预审意见"),
        ),
        migrations.AddField(
            model_name="application",
            name="team_leader_note",
            field=models.TextField(blank=True, null=True, verbose_name="组长审批意见"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="team",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="所属团队"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_TEAM", "待组长审批"),
                    ("PENDING_PRE", "待资源预审"),
                    ("PENDING_FINAL", "待部门终审"),
                    ("APPROVED", "已审批(待执行)"),
                    ("REJECTED", "已驳回"),
                    ("EXECUTED", "已执行"),
                    ("CANCELLED", "已撤回"),
                    ("RELEASED", "已释放"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("APPLICANT", "申请人"),
                    ("TEAM_LEADER", "组长"),
                    ("APPROVER", "预审人/审批人"),
                    ("DEPT_HEAD", "部门负责人"),
                    ("EXECUTOR", "执行人"),
                    ("ADMIN", "管理员"),
                ],
                default="APPLICANT",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
    ]
