# Generated by Django 5.0.6 on 2026-05-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0010_application_final_approver_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_TEAM", "待组长审批"),
                    ("PENDING_PRE", "待资源预审"),
                    ("PENDING_FINAL", "待部门终审"),
                    ("APPROVED", "已审批(待执行)"),
                    ("REJECTED", "已驳回"),
                    ("EXECUTED", "已执行"),
                    ("CANCELLED", "已撤回"),
                    ("RELEASED", "已释放"),
                ],
                default="PENDING_TEAM",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
