# Generated by Django 5.0.6 on 2026-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0011_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="cardForm",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="申请卡形态"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="cardType",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="申请卡型号"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="project",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="受益项目"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_TEAM", "待组长审批"),
                    ("PENDING_PRE", "待资源预审"),
                    ("PENDING_FINAL", "待部门终审"),
                    ("APPROVED", "已审批(待执行)"),
                    ("REJECTED", "已驳回"),
                    ("EXECUTED", "已执行"),
                    ("CANCELLED", "已撤回"),
                    ("RELEASED", "已释放"),
                ],
                db_index=True,
                default="PENDING_TEAM",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="team",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="所在团队"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="team",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="所属团队",
            ),
        ),
        migrations.AlterField(
            model_name="resourceasset",
            name="card_form",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="卡资源形态",
            ),
        ),
        migrations.AlterField(
            model_name="resourceasset",
            name="card_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="卡资源型号",
            ),
        ),
        migrations.AlterField(
            model_name="resourceasset",
            name="region",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="地域",
            ),
        ),
        migrations.AlterField(
            model_name="resourceasset",
            name="status",
            field=models.CharField(
                choices=[("IDLE", "闲置"), ("IN_USE", "使用中"), ("FAULT", "故障")],
                db_index=True,
                default="IDLE",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
