# Generated by Django 5.0.6 on 2026-05-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0012_alter_application_cardform_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuefeedback",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="feedback_images/",
                verbose_name="反馈图片",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="账号"),
        ),
    ]
