# Generated by Django 5.0.6 on 2026-05-29 06:19

import resource_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0013_issuefeedback_image_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置键"
                    ),
                ),
                ("value", models.CharField(max_length=200, verbose_name="配置值")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="配置描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "系统全局设置",
                "verbose_name_plural": "系统全局设置",
            },
        ),
        migrations.AlterField(
            model_name="resourceasset",
            name="password",
            field=resource_app.models.EncryptedCharField(
                blank=True, max_length=250, null=True, verbose_name="密码"
            ),
        ),
    ]
