# Generated by Django 5.0.6 on 2026-06-01 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0014_systemsetting_alter_resourceasset_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuefeedback",
            name="image",
        ),
        migrations.CreateModel(
            name="FeedbackImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="feedback_images/", verbose_name="图片"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="resource_app.issuefeedback",
                        verbose_name="所属反馈",
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈图片",
                "verbose_name_plural": "反馈图片",
            },
        ),
    ]
