# Generated by Django 5.0.6 on 2026-06-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0015_remove_issuefeedback_image_feedbackimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="allocation_details",
            field=models.JSONField(blank=True, null=True, verbose_name="分配卡池详情"),
        ),
        migrations.AddField(
            model_name="application",
            name="card_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="计算卡张数"),
        ),
        migrations.AddField(
            model_name="application",
            name="card_days",
            field=models.IntegerField(blank=True, null=True, verbose_name="计算卡天数"),
        ),
        migrations.CreateModel(
            name="SystemNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_email",
                    models.CharField(max_length=150, verbose_name="接收账号"),
                ),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "发送中"),
                            ("SUCCESS", "发送成功"),
                            ("FAILED", "发送失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通知日志",
                "verbose_name_plural": "通知日志管理",
            },
        ),
    ]
