# Generated by Django 5.0.6 on 2026-06-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0016_application_allocation_details_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="role",
            new_name="roles",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="roles",
            field=models.CharField(
                default="APPLICANT", max_length=255, verbose_name="用户角色(多选)"
            ),
        ),
    ]
