# Generated by Django 5.0.6 on 2026-06-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0017_remove_customuser_role_customuser_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="coordination_details",
            field=models.JSONField(blank=True, null=True, verbose_name="协调抽调详情"),
        ),
    ]
