# Generated by Django 5.0.6 on 2026-06-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0018_application_coordination_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "verbose_name": "申请单",
                "verbose_name_plural": "④ 申请单列表（历史单据导入与查看）",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "② 用户管理（账号/角色/团队）",
            },
        ),
        migrations.AlterModelOptions(
            name="issuefeedback",
            options={"verbose_name": "问题反馈", "verbose_name_plural": "⑥ 问题反馈"},
        ),
        migrations.AlterModelOptions(
            name="resourceasset",
            options={
                "verbose_name": "物料资产",
                "verbose_name_plural": "⑤ 物料资产（服务器/设备台账）",
            },
        ),
        migrations.AlterModelOptions(
            name="resourceinventory",
            options={
                "verbose_name": "卡池库存",
                "verbose_name_plural": "③ 卡池库存（各型号总量与余量）",
            },
        ),
        migrations.AlterModelOptions(
            name="systemnotificationlog",
            options={
                "verbose_name": "通知日志",
                "verbose_name_plural": "⑦ 通知日志（催办记录）",
            },
        ),
        migrations.AlterModelOptions(
            name="systemoption",
            options={
                "verbose_name": "下拉选项",
                "verbose_name_plural": "① 下拉选项配置（团队/型号/形态/项目/地域）【最先配置】",
            },
        ),
        migrations.AlterModelOptions(
            name="systemsetting",
            options={
                "verbose_name": "全局设置",
                "verbose_name_plural": "⑧ 全局设置（高级配置）",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="账号"
            ),
        ),
    ]
