# Generated by Django 5.0.6 on 2026-06-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resource_app",
            "0019_alter_application_options_alter_customuser_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceasset",
            name="card_count",
            field=models.PositiveIntegerField(
                default=8,
                help_text="该台设备的GPU卡数量，裸机一般为8卡",
                verbose_name="卡数量",
            ),
        ),
    ]
