# Generated by Django 5.0.6 on 2026-06-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_app", "0020_resourceasset_card_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourceasset",
            name="allocated_application",
        ),
        migrations.AddField(
            model_name="resourceasset",
            name="used_cards",
            field=models.PositiveIntegerField(
                default=0,
                help_text="该物理机目前已被分配的卡数量",
                verbose_name="已用卡数",
            ),
        ),
        migrations.AlterField(
            model_name="resourceasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("IDLE", "闲置"),
                    ("IN_USE", "使用中(满载)"),
                    ("PARTIAL", "部分分配"),
                    ("FAULT", "故障"),
                ],
                db_index=True,
                default="IDLE",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="AssetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_cards",
                    models.PositiveIntegerField(default=1, verbose_name="分配卡数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_allocations",
                        to="resource_app.application",
                        verbose_name="申请单",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="resource_app.resourceasset",
                        verbose_name="物理资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产分配明细",
                "verbose_name_plural": "⑥ 资产分配明细",
                "unique_together": {("asset", "application")},
            },
        ),
    ]
